[build]
  # Mengatur direktori deploy ke root tempat file HTML, CSS, dan gambar berada
  publish = "."
  # Menghindari build command agar Netlify langsung menyajikan file statis
  command = ""

# Pengaturan redirect & rewrite
[[redirects]]
  from = "/about"
  to = "/About.html"
  status = 200

[[redirects]]
  from = "/elektronik"
  to = "/Elektronik.html"
  status = 200

[[redirects]]
  from = "/calculator"
  to = "/calculator.html"
  status = 200

[[redirects]]
  from = "/simulator"
  to = "/simulator.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
